### ISSUE TITLE
ModuleNotFoundError: No module named 'laser'

### ISSUE THREAD

**Issue by ghost** [raymondhs/fairseq-laser#1]
I ran fairseq-train as next command:

```sh
fairseq-train ../data/laser/data-bin/ \
  --max-epoch 7 \
  --ddp-backend=no_c10d \
  --task translation_laser --lang-pairs ne-en \
  --arch laser_lstm_artetxe \
  --encoder-num-layers 5 \
  --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
  --lr 0.001 --lr-scheduler fixed \
  --weight-decay 0.0 --criterion cross_entropy \
  --save-dir checkpoints/laser_lstm \
  --max-tokens 3584 \
  --update-freq 8 \
  --log-interval 50 \
  --user-dir ./fairseq-laser/laser
```

However, ```No module named 'laser'``` was displayed while training.

Could you please tell me how to fix this?

```sh
| distributed init (rank 0): tcp://localhost:16810
| distributed init (rank 1): tcp://localhost:16810
| initialized host wmt19_pcf as rank 1
| initialized host wmt19_pcf as rank 0
Namespace(adam_betas='(0.9, 0.98)', adam_eps=1e-08, arch='laser_lstm_artetxe', best_checkpoint_metric='loss', bpe=None, bucket_cap_mb=25, clip_norm=0.0, cpu=False, criterion='cross_entropy', curriculum=0, data='../data/laser/data-bin/', dataset_impl=None, ddp_backend='no_c10d', decoder_dropout=0.1, decoder_embed_dim=320, decoder_hidden_dim=2048, decoder_langtok=False, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method='tcp://localhost:16810', distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=2, encoder_dropout=0.1, encoder_embed_dim=320, encoder_hidden_dim=512, encoder_langtok=None, encoder_num_layers=5, find_unused_parameters=False, fix_batches_to_gpus=False, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_updates=-1, keep_last_epochs=-1, lang_embed_dim=32, lang_embeddings=True, lang_pairs='ne-en', lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=50, lr=[0.001], lr_scheduler='fixed', lr_shrink=0.1, max_epoch=7, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=3584, max_tokens_valid=3584, max_update=0, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, num_workers=1, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints/laser_lstm', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation_laser', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, train_subset='train', update_freq=[8], upsample_primary=1, use_bmuf=False, user_dir='./fairseq-laser/laser', valid_subset='valid', validate_interval=1, warmup_updates=0, weight_decay=0.0)
| [en] dictionary: 49880 types
| [ne] dictionary: 49880 types
| loaded 5457 examples from: ../data/laser/data-bin/valid.ne-en.ne
| loaded 5457 examples from: ../data/laser/data-bin/valid.ne-en.en
| ../data/laser/data-bin/ valid ne-en 5457 examples
/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py:275: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  for key in self.keys
/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py:275: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  for key in self.keys
LaserLSTMModel(
  (models): ModuleDict(
    (ne-en): FairseqModel(
      (encoder): LaserLSTMEncoder(
        (embed_tokens): Embedding(49880, 320, padding_idx=1)
        (lstm): LSTM(320, 512, num_layers=5, dropout=0.1, bidirectional=True)
      )
      (decoder): LaserLSTMDecoder(
        (embed_tokens): Embedding(49880, 320, padding_idx=1)
        (embed_lang): Embedding(3, 32, padding_idx=0)
        (lstm): LSTM(1376, 2048)
        (sentemb_hidden_proj): Linear(in_features=1024, out_features=2048, bias=True)
        (sentemb_cell_proj): Linear(in_features=1024, out_features=2048, bias=True)
        (fc_out): Linear(in_features=2048, out_features=49880, bias=True)
      )
    )
  )
)
| model laser_lstm_artetxe, criterion CrossEntropyCriterion
| num. model params: 195006264 (num. trained: 195006264)
| training on 2 GPUs
| max tokens per GPU = 3584 and max sentences per GPU = None
| no existing checkpoint found checkpoints/laser_lstm/checkpoint_last.pt
| loading train data for epoch 0
| loaded 11328074 examples from: ../data/laser/data-bin/train.ne-en.ne
| loaded 11328074 examples from: ../data/laser/data-bin/train.ne-en.en
| ../data/laser/data-bin/ train ne-en 11328074 examples
| epoch 001:   0%|                                     | 0/2577 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'laser'
```

**Comment by raymondhs** [comment]
Hello, sorry for late reply!
Could you try running the command from inside `fairseq-laser` directory?
